package com.genustin.easy;


/**
 * Created by Genustin on 2016/9/25.
 * Find the difference
 * <p>
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
public class P398 {
    public char findTheDifference(String s, String t) {
        int[] alpha = new int[26];
//      int[] alpha = new int['z'+1];
        for (int i = 0; i < t.length(); i++) {
            alpha[t.charAt(i) - 'a']++;
        }
        for (int i = 0; i < s.length(); i++) {
            alpha[s.charAt(i) - 'a']--;
        }
        for (int i = 0; i < 26; i++) {
            if (alpha[i] == 1)
                return (char) (i + 'a');
        }

        // no use, comfort compiler
        return 'a';
    }

    public static void main(String[] args) {
        P398 sol = new P398();
        System.out.println(sol.findTheDifference("aaa", "aaaz"));
    }
}
